import { FoodCategory, NutritionType, NutritionUnit } from "@aicoach/shared";

export const xlsHeaders = [
	"alim_grp_code",
	"alim_ssgrp_code",
	"alim_ssssgrp_code",
	"alim_grp_nom_eng",
	"alim_ssgrp_nom_eng",
	"alim_ssssgrp_nom_eng",
	"alim_code",
	"alim_nom_eng",
	"alim_nom_sci",
	"Energy, Regulation EU No 1169/2011 (kJ/100g)",
	"Energy, Regulation EU No 1169/2011 (kcal/100g)",
	"Energy, N x Jones' factor, with fibres (kJ/100g)",
	"Energy, N x Jones' factor, with fibres (kcal/100g)",
	"Water (g/100g)",
	"Protein (g/100g)",
	"Protein, crude, N x 6.25 (g/100g)",
	"Carbohydrate (g/100g)",
	"Fat (g/100g)",
	"Sugars (g/100g)",
	"fructose (g/100g)",
	"galactose (g/100g)",
	"glucose (g/100g)",
	"lactose (g/100g)",
	"maltose (g/100g)",
	"sucrose (g/100g)",
	"Starch (g/100g)",
	"Fibres (g/100g)",
	"Polyols (g/100g)",
	"Ash (g/100g)",
	"Alcohol (g/100g)",
	"Organic acids (g/100g)",
	"FA saturated (g/100g)",
	"FA mono (g/100g)",
	"FA poly (g/100g)",
	"FA 4:0 (g/100g)",
	"FA 6:0 (g/100g)",
	"FA 8:0 (g/100g)",
	"FA 10:0 (g/100g)",
	"FA 12:0 (g/100g)",
	"FA 14:0 (g/100g)",
	"FA 16:0 (g/100g)",
	"FA 18:0 (g/100g)",
	"FA 18:1 n-9 cis (g/100g)",
	"FA 18:2 9c,12c (n-6) (g/100g)",
	"FA 18:3 c9,c12,c15 (n-3) (g/100g)",
	"FA 20:4 5c,8c,11c,14c (n-6) (g/100g)",
	"FA 20:5 5c,8c,11c,14c,17c (n-3) EPA (g/100g)",
	"FA 22:6 4c,7c,10c,13c,16c,19c (n-3) DHA (g/100g)",
	"Cholesterol (mg/100g)",
	"Salt (g/100g)",
	"Calcium (mg/100g)",
	"Chloride (mg/100g)",
	"Copper (mg/100g)",
	"Iron (mg/100g)",
	"Iodine (µg/100g)",
	"Magnesium (mg/100g)",
	"Manganese (mg/100g)",
	"Phosphorus (mg/100g)",
	"Potassium (mg/100g)",
	"Selenium (µg/100g)",
	"Sodium (mg/100g)",
	"Zinc (mg/100g)",
	"Retinol (µg/100g)",
	"Beta-carotene (µg/100g)",
	"Vitamin D (µg/100g)",
	"Vitamin E (mg/100g)",
	"Vitamin K1 (µg/100g)",
	"Vitamin K2 (µg/100g)",
	"Vitamin C (mg/100g)",
	"Vitamin B1 or Thiamin (mg/100g)",
	"Vitamin B2 or Riboflavin (mg/100g)",
	"Vitamin B3 or Niacin (mg/100g)",
	"Vitamin B5 or Pantothenic acid (mg/100g)",
	"Vitamin B6 (mg/100g)",
	"Vitamin B9 or Folate (µg/100g)",
	"Vitamin B12 (µg/100g)"
];

export const xlsToNutritionMap: Record<string, { type: NutritionType; unit: NutritionUnit }> = {
	"Energy, Regulation EU No 1169/2011 (kcal/100g)": { type: "Calories", unit: "kcal" },
	"Water (g/100g)": { type: "Water", unit: "g" },
	"Protein (g/100g)": { type: "Protein", unit: "g" },
	"Carbohydrate (g/100g)": { type: "Carbohydrates", unit: "g" },
	"Fat (g/100g)": { type: "Total Fat", unit: "g" },
	"Sugars (g/100g)": { type: "Sugar", unit: "g" },
	"fructose (g/100g)": { type: "Fructose", unit: "g" },
	"galactose (g/100g)": { type: "Galactose", unit: "g" },
	"glucose (g/100g)": { type: "Glucose", unit: "g" },
	"lactose (g/100g)": { type: "Lactose", unit: "g" },
	"maltose (g/100g)": { type: "Maltose", unit: "g" },
	"sucrose (g/100g)": { type: "Sucrose", unit: "g" },
	"Starch (g/100g)": { type: "Starch", unit: "g" },
	"Fibres (g/100g)": { type: "Fiber", unit: "g" },
	"Alcohol (g/100g)": { type: "Alcohol", unit: "g" },
	"FA saturated (g/100g)": { type: "Saturated Fat", unit: "g" },
	"FA mono (g/100g)": { type: "Monounsaturated Fat", unit: "g" },
	"FA poly (g/100g)": { type: "Polyunsaturated Fat", unit: "g" },
	"FA 18:2 9c,12c (n-6) (g/100g)": { type: "Omega-6 LA", unit: "g" },
	"FA 18:3 c9,c12,c15 (n-3) (g/100g)": { type: "Omega-3 ALA", unit: "g" },
	"FA 20:5 5c,8c,11c,14c,17c (n-3) EPA (g/100g)": { type: "Omega-3 EPA", unit: "g" },
	"FA 22:6 4c,7c,10c,13c,16c,19c (n-3) DHA (g/100g)": { type: "Omega-3 DHA", unit: "g" },
	"Cholesterol (mg/100g)": { type: "Cholesterol", unit: "mg" },
	"Sodium (mg/100g)": { type: "Sodium", unit: "mg" },
	"Salt (g/100g)": { type: "Salt", unit: "g" },
	"Calcium (mg/100g)": { type: "Calcium", unit: "mg" },
	"Copper (mg/100g)": { type: "Copper", unit: "mg" },
	"Iron (mg/100g)": { type: "Iron", unit: "mg" },
	"Iodine (µg/100g)": { type: "Iodine", unit: "µg" },
	"Magnesium (mg/100g)": { type: "Magnesium", unit: "mg" },
	"Manganese (mg/100g)": { type: "Manganese", unit: "mg" },
	"Phosphorus (mg/100g)": { type: "Phosphorus", unit: "mg" },
	"Potassium (mg/100g)": { type: "Potassium", unit: "mg" },
	"Selenium (µg/100g)": { type: "Selenium", unit: "µg" },
	"Zinc (mg/100g)": { type: "Zinc", unit: "mg" },
	"Retinol (µg/100g)": { type: "Vitamin A Retinol", unit: "µg" },
	"Beta-carotene (µg/100g)": { type: "Vitamin A Beta-Carotene", unit: "µg" },
	"Vitamin D (µg/100g)": { type: "Vitamin D", unit: "µg" },
	"Vitamin E (mg/100g)": { type: "Vitamin E", unit: "mg" },
	"Vitamin K1 (µg/100g)": { type: "Vitamin K", unit: "µg" },
	"Vitamin K2 (µg/100g)": { type: "Vitamin K", unit: "µg" },
	"Vitamin C (mg/100g)": { type: "Vitamin C", unit: "mg" },
	"Vitamin B1 or Thiamin (mg/100g)": { type: "Thiamin", unit: "mg" },
	"Vitamin B2 or Riboflavin (mg/100g)": { type: "Riboflavin", unit: "mg" },
	"Vitamin B3 or Niacin (mg/100g)": { type: "Niacin", unit: "mg" },
	"Vitamin B5 or Pantothenic acid (mg/100g)": { type: "Pantothenic Acid", unit: "mg" },
	"Vitamin B6 (mg/100g)": { type: "Vitamin B-6", unit: "mg" },
	"Vitamin B9 or Folate (µg/100g)": { type: "Folate", unit: "µg" },
	"Vitamin B12 (µg/100g)": { type: "Vitamin B-12", unit: "µg" }
};

export const xlsToFoodCategoryMap: Record<string, FoodCategory> = {
	"mixed salads": "Mixed Dishes",
	"soups": "Soups and Sauces",
	"dishes": "Mixed Dishes",
	"pizzas": "Mixed Dishes",
	"crepe and pies": "Baked Products",
	"sandwiches": "Mixed Dishes",
	"savoury pastries and other starters": "Baked Products",
	"vegetables": "Vegetables",
	"potatoes and other tubers": "Vegetables",
	"legumes": "Legumes & Pulses",
	"fruits": "Fruits",
	"nuts and seeds": "Nuts & Seeds",
	"pasta": "Grains & Cereals",
	"rice and grains": "Grains & Cereals",
	"breads and similar": "Baked Products",
	"savoury biscuits": "Sweets & Snacks",
	"cooked meat": "Other Proteins",
	"raw meat": "Other Proteins",
	"delicatessen meat and similar": "Other Proteins",
	"other meat products": "Other Proteins",
	"fish, cooked": "Fish",
	"fish, raw": "Fish",
	"seafood, cooked": "Fish",
	"seafood, raw": "Fish",
	"fish products": "Fish",
	"eggs": "Eggs",
	"meat substitute": "Other Proteins",
	"milk": "Dairy & Alternatives",
	"dairy products and similar": "Dairy & Alternatives",
	"cheese and similar": "Dairy & Alternatives",
	"cream and similar": "Dairy & Alternatives",
	"water": "Beverages",
	"non-alcoholic beverages": "Beverages",
	"alcoholic beverages": "Beverages",
	"sugars and honey": "Sweets & Snacks",
	"chocolate and chocolate products": "Sweets & Snacks",
	"non-chocolate confectionery": "Sweets & Snacks",
	"jam": "Sweets & Snacks",
	"Viennese pastries": "Baked Products",
	"sweet biscuits": "Sweets & Snacks",
	"breakfast cereals": "Grains & Cereals",
	"cereal bars": "Grains & Cereals",
	"cakes and pastry": "Sweets & Snacks",
	"-": "Other",
	"ice cream": "Sweets & Snacks",
	"sorbet": "Sweets & Snacks",
	"frozen desserts": "Sweets & Snacks",
	"butters": "Fats & Oils",
	"vegetable oils": "Fats & Oils",
	"margarines": "Fats & Oils",
	"fish oils": "Fats & Oils",
	"other fats": "Fats & Oils",
	"sauces": "Soups and Sauces",
	"condiments": "Soups and Sauces",
	"cooking aids": "Soups and Sauces",
	"salts": "Spices and Herbs",
	"spices": "Spices and Herbs",
	"herbs": "Spices and Herbs",
	"seaweed": "Vegetables",
	"foods for particular nutritional uses": "Supplements",
	"miscellaneous ingredients": "Other",
	"miscellaneous ingredients for vegetarian": "Other",
	"baby milk and beverages": "Baby Foods",
	"baby dishes": "Baby Foods",
	"baby deserts": "Baby Foods",
	"baby biscuits and cereals": "Baby Foods"
} as const;
