import { FoodCategory, NutritionType, NutritionUnit } from "@aicoach/shared";

export const xlsHeaders = [
	"Food Code",
	"Food Name",
	"Description",
	"Group",
	"Previous",
	"Main data references",
	"Footnote",
	"Water (g)",
	"Total nitrogen (g)",
	"Protein (g)",
	"Fat (g)",
	"Carbohydrate (g)",
	"Energy (kcal) (kcal)",
	"Energy (kJ) (kJ)",
	"Starch (g)",
	"Oligosaccharide (g)",
	"Total sugars (g)",
	"Glucose (g)",
	"Galactose (g)",
	"Fructose (g)",
	"Sucrose (g)",
	"Maltose (g)",
	"Lactose (g)",
	"Alcohol (g)",
	"NSP (g)",
	"AOAC fibre (g)",
	"Satd FA /100g FA (g)",
	"Satd FA /100g fd (g)",
	"n-6 poly /100g FA (g)",
	"n-6 poly /100g food (g)",
	"n-3 poly /100g FA (g)",
	"n-3 poly /100g food (g)",
	"cis‑Mono FA /100g FA (g)",
	"cis‑Mono FA /100g Food (g)",
	"Mono FA/ 100g FA (g)",
	"Mono FA /100g food (g)",
	"cis‑Polyu FA /100g FA (g)",
	"cis‑Poly FA /100g Food (g)",
	"Poly FA /100g FA (g)",
	"Poly FA /100g food (g)",
	"Sat FA excl Br /100g FA (g)",
	"Sat FA excl Br /100g food (g)",
	"Branched chain FA /100g FA (g)",
	"Branched chain FA /100g food (g)",
	"Trans FAs /100g FA (g)",
	"Trans FAs /100g food (g)",
	"Cholesterol (mg)"
];

// Mapping from COFID spreadsheet column names to nutrition types in our system
export const xlsToNutritionMap: Record<string, { type: NutritionType; unit: NutritionUnit }> = {
	"Energy (kcal) (kcal)": { type: "Calories", unit: "kcal" },
	"Water (g)": { type: "Water", unit: "g" },
	"Protein (g)": { type: "Protein", unit: "g" },
	"Fat (g)": { type: "Total Fat", unit: "g" },
	"Carbohydrate (g)": { type: "Carbohydrates", unit: "g" },
	"Starch (g)": { type: "Starch", unit: "g" },
	"Total sugars (g)": { type: "Sugar", unit: "g" },
	"Glucose (g)": { type: "Glucose", unit: "g" },
	"Galactose (g)": { type: "Galactose", unit: "g" },
	"Fructose (g)": { type: "Fructose", unit: "g" },
	"Sucrose (g)": { type: "Sucrose", unit: "g" },
	"Maltose (g)": { type: "Maltose", unit: "g" },
	"Lactose (g)": { type: "Lactose", unit: "g" },
	"Alcohol (g)": { type: "Alcohol", unit: "g" },
	"NSP (g)": { type: "Fiber", unit: "g" },
	"AOAC fibre (g)": { type: "Fiber", unit: "g" },
	"Satd FA /100g fd (g)": { type: "Saturated Fat", unit: "g" },
	"n-6 poly /100g food (g)": { type: "Omega-6 Total", unit: "g" },
	"n-3 poly /100g food (g)": { type: "Omega-3 Total", unit: "g" },
	"cis-Mono FA /100g Food (g)": { type: "Monounsaturated Fat", unit: "g" },
	"Mono FA /100g food (g)": { type: "Monounsaturated Fat", unit: "g" },
	"cis-Poly FA /100g Food (g)": { type: "Polyunsaturated Fat", unit: "g" },
	"Poly FA /100g food (g)": { type: "Polyunsaturated Fat", unit: "g" },
	"Trans FAs /100g food (g)": { type: "Trans Fat", unit: "g" },
	"Cholesterol (mg)": { type: "Cholesterol", unit: "mg" }
};

export const cofidToFoodCategoryMap: Record<string, FoodCategory> = {
	// Cereals and cereal products
	"A":   "Grains & Cereals",
	"AA":  "Grains & Cereals",
	"AB":  "Mixed Dishes",
	"AC":  "Grains & Cereals",
	"AD":  "Grains & Cereals",
	"AE":  "Mixed Dishes",
	"AF":  "Baked Products",
	"AG":  "Baked Products",
	"AI":  "Grains & Cereals",
	"AK":  "Baby Foods",
	"AM":  "Sweets & Snacks",
	"AN":  "Sweets & Snacks",
	"AO":  "Baked Products",
	"AP":  "Baked Products",
	"AS":  "Sweets & Snacks",
	"AT":  "Sweets & Snacks",

	// Milk and milk products
	"B":    "Dairy & Alternatives",
	"BA":   "Dairy & Alternatives",
	"BAB":  "Dairy & Alternatives",
	"BAE":  "Dairy & Alternatives",
	"BAH":  "Dairy & Alternatives",
	"BAK":  "Dairy & Alternatives",
	"BAN":  "Dairy & Alternatives",
	"BAR":  "Dairy & Alternatives",
	"BC":   "Dairy & Alternatives",
	"BF":   "Baby Foods",
	"BFD":  "Baby Foods",
	"BFG":  "Baby Foods",
	"BFJ":  "Baby Foods",
	"BFP":  "Baby Foods",
	"BH":   "Beverages",
	"BJ":   "Dairy & Alternatives",
	"BJC":  "Dairy & Alternatives",
	"BJF":  "Dairy & Alternatives",
	"BJL":  "Dairy & Alternatives",
	"BJP":  "Dairy & Alternatives",
	"BJS":  "Dairy & Alternatives",
	"BL":   "Dairy & Alternatives",
	"BN":   "Dairy & Alternatives",
	"BNE":  "Dairy & Alternatives",
	"BNH":  "Dairy & Alternatives",
	"BNS":  "Dairy & Alternatives",
	"BP":   "Sweets & Snacks",
	"BR":   "Sweets & Snacks",
	"BV":   "Mixed Dishes",

	// Eggs
	"C":    "Eggs",
	"CA":   "Eggs",
	"CD":   "Mixed Dishes",
	"CDE":  "Mixed Dishes",
	"CDH":  "Sweets & Snacks",

	// Vegetables
	"D":    "Vegetables",
	"DA":   "Vegetables",
	"DAE":  "Vegetables",
	"DAM":  "Vegetables",
	"DAP":  "Sweets & Snacks",
	"DAR":  "Vegetables",
	"DB":   "Legumes & Pulses",
	"DF":   "Legumes & Pulses",
	"DG":   "Vegetables",
	"DI":   "Vegetables",
	"DR":   "Mixed Dishes",

	// Fruit
	"F":    "Fruits",
	"FA":   "Fruits",
	"FC":   "Beverages",

	// Nuts & seeds
	"G":    "Nuts & Seeds",
	"GA":   "Nuts & Seeds",

	// Herbs & spices
	"H":    "Spices and Herbs",

	// Fish & fish products
	"J":    "Fish",
	"JA":   "Fish",
	"JC":   "Fish",
	"JK":   "Fish",
	"JM":   "Fish",
	"JR":   "Fish",

	// Meat & meat products
	"M":    "Other Proteins",
	"MA":   "Other Proteins",
	"MAA":  "Pork",
	"MAC":  "Beef & Lamb",
	"MAE":  "Beef & Lamb",
	"MAG":  "Pork",
	"MAI":  "Beef & Lamb",
	"MC":   "Poultry",
	"MCA":  "Poultry",
	"MCC":  "Poultry",
	"MCE":  "Poultry",
	"MCG":  "Game Meats",
	"MCI":  "Game Meats",
	"MCK":  "Game Meats",
	"MCM":  "Game Meats",
	"MCO":  "Poultry",
	"ME":   "Game Meats",
	"MEA":  "Game Meats",
	"MEC":  "Game Meats",
	"MEE":  "Game Meats",
	"MG":   "Other Proteins",
	"MBG":  "Mixed Dishes",
	"MI":   "Other Proteins",
	"MIG":  "Other Proteins",
	"MR":   "Mixed Dishes",

	// Fats & oils
	"O":    "Fats & Oils",
	"OA":   "Fats & Oils",
	"OB":   "Fats & Oils",
	"OC":   "Fats & Oils",
	"OE":   "Fats & Oils",
	"OF":   "Fats & Oils",

	// Beverages
	"P":    "Beverages",
	"PA":   "Beverages",
	"PAA":  "Beverages",
	"PAC":  "Beverages",
	"PC":   "Beverages",
	"PCA":  "Beverages",
	"PCC":  "Beverages",
	"PE":   "Beverages",

	// Alcoholic beverages
	"Q":    "Beverages",
	"QA":   "Beverages",
	"QC":   "Beverages",
	"QE":   "Beverages",
	"QF":   "Beverages",
	"QG":   "Beverages",
	"QI":   "Beverages",
	"QK":   "Beverages",

	// Sugars, preserves & snacks
	"S":    "Sweets & Snacks",
	"SC":   "Sweets & Snacks",
	"SE":   "Sweets & Snacks",
	"SEA":  "Sweets & Snacks",
	"SEC":  "Sweets & Snacks",
	"SN":   "Sweets & Snacks",
	"SNA":  "Sweets & Snacks",
	"SNB":  "Sweets & Snacks",
	"SNC":  "Sweets & Snacks",

	// Soups, sauces & misc
	"W":    "Soups and Sauces",
	"WA":   "Soups and Sauces",
	"WAA":  "Soups and Sauces",
	"WAC":  "Soups and Sauces",
	"WAE":  "Soups and Sauces",
	"WC":   "Soups and Sauces",
	"WCD":  "Soups and Sauces",
	"WCG":  "Soups and Sauces",
	"WCN":  "Soups and Sauces",
	"WE":   "Soups and Sauces",
	"WY":   "Other",
  } as const;
