import { FoodCategory, NutritionType, NutritionUnit } from "@aicoach/shared";

export const xlsHeaders = [
	"Food Code",
	"Food Name",
	"Description",
	"Group",
	"Previous",
	"Main data references",
	"Footnote",
	"Water (g)",
	"Total nitrogen (g)",
	"Protein (g)",
	"Fat (g)",
	"Carbohydrate (g)",
	"Energy (kcal) (kcal)",
	"Energy (kJ) (kJ)",
	"Starch (g)",
	"Oligosaccharide (g)",
	"Total sugars (g)",
	"Glucose (g)",
	"Galactose (g)",
	"Fructose (g)",
	"Sucrose (g)",
	"Maltose (g)",
	"Lactose (g)",
	"Alcohol (g)",
	"NSP (g)",
	"AOAC fibre (g)",
	"Satd FA /100g FA (g)",
	"Satd FA /100g fd (g)",
	"n-6 poly /100g FA (g)",
	"n-6 poly /100g food (g)",
	"n-3 poly /100g FA (g)",
	"n-3 poly /100g food (g)",
	"cis‑Mono FA /100g FA (g)",
	"cis‑Mono FA /100g Food (g)",
	"Mono FA/ 100g FA (g)",
	"Mono FA /100g food (g)",
	"cis‑Polyu FA /100g FA (g)",
	"cis‑Poly FA /100g Food (g)",
	"Poly FA /100g FA (g)",
	"Poly FA /100g food (g)",
	"Sat FA excl Br /100g FA (g)",
	"Sat FA excl Br /100g food (g)",
	"Branched chain FA /100g FA (g)",
	"Branched chain FA /100g food (g)",
	"Trans FAs /100g FA (g)",
	"Trans FAs /100g food (g)",
	"Cholesterol (mg)"
];

// Mapping from COFID spreadsheet column names to nutrition types in our system
export const xlsToNutritionMap: Record<string, { type: NutritionType; unit: NutritionUnit }> = {
	"Energy (kcal) (kcal)": { type: "Calories", unit: "kcal" },
	"Water (g)": { type: "Water", unit: "g" },
	"Protein (g)": { type: "Protein", unit: "g" },
	"Fat (g)": { type: "Total Fat", unit: "g" },
	"Carbohydrate (g)": { type: "Carbohydrates", unit: "g" },
	"Starch (g)": { type: "Starch", unit: "g" },
	"Total sugars (g)": { type: "Sugar", unit: "g" },
	"Glucose (g)": { type: "Glucose", unit: "g" },
	"Galactose (g)": { type: "Galactose", unit: "g" },
	"Fructose (g)": { type: "Fructose", unit: "g" },
	"Sucrose (g)": { type: "Sucrose", unit: "g" },
	"Maltose (g)": { type: "Maltose", unit: "g" },
	"Lactose (g)": { type: "Lactose", unit: "g" },
	"Alcohol (g)": { type: "Alcohol", unit: "g" },
	"NSP (g)": { type: "Fiber", unit: "g" },
	"AOAC fibre (g)": { type: "Fiber", unit: "g" },
	"Satd FA /100g fd (g)": { type: "Saturated Fat", unit: "g" },
	"n-6 poly /100g food (g)": { type: "Omega-6 Total", unit: "g" },
	"n-3 poly /100g food (g)": { type: "Omega-3 Total", unit: "g" },
	"cis-Mono FA /100g Food (g)": { type: "Monounsaturated Fat", unit: "g" },
	"Mono FA /100g food (g)": { type: "Monounsaturated Fat", unit: "g" },
	"cis-Poly FA /100g Food (g)": { type: "Polyunsaturated Fat", unit: "g" },
	"Poly FA /100g food (g)": { type: "Polyunsaturated Fat", unit: "g" },
	"Trans FAs /100g food (g)": { type: "Trans Fat", unit: "g" },
	"Cholesterol (mg)": { type: "Cholesterol", unit: "mg" }
};

export const xlsToFoodCategoryMap: Record<string, FoodCategory> = {
	// Fruits
	"F": "Fruits",
	"FA": "Fruits",

	// Vegetables
	"D": "Vegetables",
	"DA": "Vegetables",
	"DAE": "Vegetables",
	"DAM": "Vegetables",
	"DG": "Vegetables",
	"DI": "Vegetables",

	// Legumes & Pulses
	"DB": "Legumes & Pulses",
	"DF": "Legumes & Pulses",

	// Grains & Cereals
	"A": "Grains & Cereals",
	"AA": "Grains & Cereals",
	"AC": "Grains & Cereals",
	"AD": "Grains & Cereals",
	"AI": "Grains & Cereals",

	// Baked Products
	"AF": "Baked Products",
	"AG": "Baked Products",
	"AM": "Baked Products",
	"AN": "Baked Products",
	"AO": "Baked Products",
	"AP": "Baked Products",
	"Viennese pastries": "Baked Products", // if this literal key appears

	// Baby Foods
	"AK": "Baby Foods",
	"BF": "Baby Foods",
	"BFD": "Baby Foods",
	"BFG": "Baby Foods",
	"BFJ": "Baby Foods",
	"BFP": "Baby Foods",

	// Dairy & Alternatives
	"B": "Dairy & Alternatives",
	"BA": "Dairy & Alternatives",
	"BAB": "Dairy & Alternatives",
	"BAE": "Dairy & Alternatives",
	"BAH": "Dairy & Alternatives",
	"BAK": "Dairy & Alternatives",
	"BAN": "Dairy & Alternatives",
	"BAR": "Dairy & Alternatives",
	"BC": "Dairy & Alternatives",
	"BH": "Dairy & Alternatives",
	"BJ": "Dairy & Alternatives",
	"BJC": "Dairy & Alternatives",
	"BJF": "Dairy & Alternatives",
	"BJL": "Dairy & Alternatives",
	"BJP": "Dairy & Alternatives",
	"BJS": "Dairy & Alternatives",
	"BL": "Dairy & Alternatives",
	"BN": "Dairy & Alternatives",
	"BNE": "Dairy & Alternatives",
	"BNH": "Dairy & Alternatives",
	"BNS": "Dairy & Alternatives",

	// Eggs
	"C": "Eggs",
	"CA": "Eggs",

	// Mixed Dishes
	"AB": "Mixed Dishes",
	"AE": "Mixed Dishes",
	"CD": "Mixed Dishes",
	"CDE": "Mixed Dishes",
	"DR": "Mixed Dishes",
	"MR": "Mixed Dishes",
	"BV": "Mixed Dishes",
	"pizzas": "Mixed Dishes", // if lower-case literal
	"sandwiches": "Mixed Dishes",
	"mixed salads": "Mixed Dishes",
	"dishes": "Mixed Dishes",

	// Sweets & Snacks
	"AS": "Sweets & Snacks",
	"AT": "Sweets & Snacks",
	"BP": "Sweets & Snacks",
	"BR": "Sweets & Snacks",
	"CDH": "Sweets & Snacks",
	"S": "Sweets & Snacks",
	"SN": "Sweets & Snacks",
	"SNA": "Sweets & Snacks",
	"SNB": "Sweets & Snacks",
	"SNC": "Sweets & Snacks",
	"savoury biscuits": "Sweets & Snacks",
	"sweet biscuits": "Sweets & Snacks",
	"cakes and pastry": "Sweets & Snacks",
	"cakes and pie": "Sweets & Snacks",
	"ice cream": "Sweets & Snacks",
	"sorbet": "Sweets & Snacks",
	"frozen desserts": "Sweets & Snacks",
	"sugars and honey": "Sweets & Snacks",
	"chocolate and chocolate products": "Sweets & Snacks",
	"non-chocolate confectionery": "Sweets & Snacks",
	"jam": "Sweets & Snacks",
	"buns and pastries": "Sweets & Snacks",
	"puddings": "Sweets & Snacks",

	// Fats & Oils
	"O": "Fats & Oils",
	"OA": "Fats & Oils",
	"OB": "Fats & Oils",
	"OC": "Fats & Oils",
	"OE": "Fats & Oils",
	"OF": "Fats & Oils",
	"butters": "Fats & Oils",
	"vegetable oils": "Fats & Oils",
	"margarines": "Fats & Oils",
	"fish oils": "Fats & Oils",
	"other fats": "Fats & Oils",

	// Beverages
	"P": "Beverages",
	"PA": "Beverages",
	"PAA": "Beverages",
	"PAC": "Beverages",
	"PC": "Beverages",
	"PCA": "Beverages",
	"PCC": "Beverages",
	"PE": "Beverages",
	"water": "Beverages",
	"non-alcoholic beverages": "Beverages",
	"alcoholic beverages": "Beverages",
	"Q": "Beverages",
	"QA": "Beverages",
	"QC": "Beverages",
	"QE": "Beverages",
	"QF": "Beverages",
	"QG": "Beverages",
	"QI": "Beverages",
	"QK": "Beverages",
	"fruit juices": "Beverages", // if literal key

	// Soups and Sauces
	"W": "Soups and Sauces",
	"WA": "Soups and Sauces",
	"WAA": "Soups and Sauces",
	"WAC": "Soups and Sauces",
	"WAE": "Soups and Sauces",
	"WC": "Soups and Sauces",
	"WCD": "Soups and Sauces",
	"WCG": "Soups and Sauces",
	"WCN": "Soups and Sauces",
	"WE": "Soups and Sauces",
	"soups": "Soups and Sauces",
	"sauces": "Soups and Sauces",
	"condiments": "Soups and Sauces",
	"cooking aids": "Soups and Sauces",

	// Spices and Herbs
	"H": "Spices and Herbs",
	"salts": "Spices and Herbs",
	"spices": "Spices and Herbs",
	"herbs": "Spices and Herbs",

	// Fish
	"J": "Fish",
	"JA": "Fish",
	"JC": "Fish",
	"JK": "Fish",
	"JM": "Fish",
	"JR": "Fish",
	"finfish and shellfish products": "Fish",
	"fish, cooked": "Fish",
	"fish, raw": "Fish",
	"seafood, cooked": "Fish",
	"seafood, raw": "Fish",
	"fish products": "Fish",

	// Proteins (sub‑typed)
	"M": "Other Proteins",
	"MA": "Other Proteins",
	"MAA": "Other Proteins",
	"MAC": "Beef & Lamb",
	"MAE": "Beef & Lamb",
	"MAI": "Beef & Lamb",
	"MAG": "Pork",
	"MBG": "Other Proteins",
	"MC": "Poultry",
	"MCA": "Poultry",
	"MCC": "Poultry",
	"MCE": "Poultry",
	"MCG": "Poultry",
	"MCI": "Poultry",
	"MCK": "Poultry",
	"MCM": "Poultry",
	"MCO": "Poultry",
	"ME": "Game Meats",
	"MEA": "Game Meats",
	"MEC": "Game Meats",
	"MEE": "Game Meats",
	"MG": "Other Proteins",
	"MI": "Other Proteins",
	"MIG": "Other Proteins",
	"Sausages and Luncheon Meats": "Other Proteins",

	// Other catch‑all
	"WY": "Other",
	"-": "Other",
	"miscellaneous ingredients": "Other",
	"miscellaneous ingredients for vegetarian": "Other"
} as const;
