import { FoodCategory, NutritionType, NutritionUnit } from "@aicoach/shared";

export const foodCategoryMap: Record<string, FoodCategory> = {
	"Baby Foods": "Baby Foods",
	"Baked Products": "Baked Products",
	"Beef Products": "Proteins",
	"Beverages": "Beverages",
	"Breakfast Cereals": "Grains & Cereals",
	"Cereal Grains and Pasta": "Grains & Cereals",
	"Dairy and Egg Products": "Dairy & Alternatives",
	"Ethnic Foods": "Mixed Dishes",
	"Fast Foods": "Mixed Dishes",
	"Fats and Oils": "Fats & Oils",
	"Finfish and Shellfish Products": "Fish",
	"Fruits and Fruit Juices": "Fruits",
	"Lamb, Veal, and Game Products": "Proteins",
	"Legumes and Legume Products": "Legumes & Pulses",
	"Meals, Entrees, and Sidedishes": "Mixed Dishes",
	"Nut and Seed Products": "Nuts & Seeds",
	"Pork Products": "Proteins",
	"Poultry Products": "Proteins",
	"Restaurant Foods": "Mixed Dishes",
	"Sausages and Luncheon Meats": "Proteins",
	"Snacks": "Sweets & Snacks",
	"Soups, Sauces, and Gravies": "Soups and Sauces",
	"Spices and Herbs": "Spices and Herbs",
	"Supplements": "Supplements",
	"Sweets": "Sweets & Snacks",
	"Vegetables and Vegetable Products": "Vegetables"
} as const;

export const nutritionMap: Record<string, { type: NutritionType; unit: NutritionUnit }> = {
	"Energy": { type: "Calories", unit: "kcal" },
	"Energy (Atwater Specific Factors)": { type: "Calories", unit: "kcal" },
	"Alcohol": { type: "Alcohol", unit: "g" },
	"Total lipid (fat)": { type: "Total Fat", unit: "g" },
	"Fatty acids, total saturated": { type: "Saturated Fat", unit: "g" },
	"Fatty acids, total monounsaturated": { type: "Monounsaturated Fat", unit: "g" },
	"Fatty acids, total polyunsaturated": { type: "Polyunsaturated Fat", unit: "g" },
	"Fatty acids, total trans": { type: "Trans Fat", unit: "g" },
	"PUFA 22:6 n-3 (DHA)": { type: "Omega-3 DHA", unit: "g" },
	"PUFA 20:5 n-3 (EPA)": { type: "Omega-3 EPA", unit: "g" },
	"PUFA 22:5 n-3 (DPA)": { type: "Omega-3 DPA", unit: "g" },
	"PUFA 18:3 n-3 c,c,c (ALA)": { type: "Omega-3 ALA", unit: "g" },
	"PUFA 20:3 n-3": { type: "Omega-3 ETE", unit: "g" },
	"PUFA 18:2 n-6 c,c": { type: "Omega-6 LA", unit: "g" },
	"PUFA 20:3 n-6": { type: "Omega-6 DGLA", unit: "g" },
	"Carbohydrate, by difference": { type: "Carbohydrates", unit: "g" },
	"Sugars, Total": { type: "Sugar", unit: "g" },
	"Fiber, total dietary": { type: "Fiber", unit: "g" },
	"Starch": { type: "Starch", unit: "g" },
	"Protein": { type: "Protein", unit: "g" },
	"Cystine": { type: "Cystine", unit: "g" },
	"Histidine": { type: "Histidine", unit: "g" },
	"Isoleucine": { type: "Isoleucine", unit: "g" },
	"Leucine": { type: "Leucine", unit: "g" },
	"Lysine": { type: "Lysine", unit: "g" },
	"Methionine": { type: "Methionine", unit: "g" },
	"Phenylalanine": { type: "Phenylalanine", unit: "g" },
	"Threonine": { type: "Threonine", unit: "g" },
	"Tryptophan": { type: "Tryptophan", unit: "g" },
	"Tyrosine": { type: "Tyrosine", unit: "g" },
	"Valine": { type: "Valine", unit: "g" },
	"Sodium, Na": { type: "Sodium", unit: "mg" },
	"Water": { type: "Water", unit: "g" },
	"Caffeine": { type: "Caffeine", unit: "mg" },
	"Vitamin A, RAE": { type: "Vitamin A RAE", unit: "µg" },
	"Vitamin C, total ascorbic acid": { type: "Vitamin C", unit: "mg" },
	"Vitamin D (D2 + D3)": { type: "Vitamin D", unit: "µg" },
	"Vitamin E (alpha-tocopherol)": { type: "Vitamin E", unit: "mg" },
	"Vitamin K (phylloquinone)": { type: "Vitamin K", unit: "µg" },
	"Thiamin": { type: "Thiamin", unit: "mg" },
	"Riboflavin": { type: "Riboflavin", unit: "mg" },
	"Niacin": { type: "Niacin", unit: "mg" },
	"Pantothenic acid": { type: "Pantothenic Acid", unit: "mg" },
	"Vitamin B-6": { type: "Vitamin B-6", unit: "mg" },
	"Vitamin B-12": { type: "Vitamin B-12", unit: "µg" },
	"Folate, total": { type: "Folate", unit: "µg" },
	"Biotin": { type: "Biotin", unit: "µg" },
	"Choline, total": { type: "Choline", unit: "mg" },
	"Iodine, I": { type: "Iodine", unit: "µg" },
	"Zinc, Zn": { type: "Zinc", unit: "mg" },
	"Calcium, Ca": { type: "Calcium", unit: "mg" },
	"Copper, Cu": { type: "Copper", unit: "mg" },
	"Iron, Fe": { type: "Iron", unit: "mg" },
	"Magnesium, Mg": { type: "Magnesium", unit: "mg" },
	"Manganese, Mn": { type: "Manganese", unit: "mg" },
	"Phosphorus, P": { type: "Phosphorus", unit: "mg" },
	"Potassium, K": { type: "Potassium", unit: "mg" },
	"Selenium, Se": { type: "Selenium", unit: "µg" },
	"Cholesterol": { type: "Cholesterol", unit: "mg" }
};
