import { initializeApp } from "firebase-admin/app";
import { initializeFirestore } from "firebase-admin/firestore";
import { expressApiHandler } from "./express";
import { accountDeletionRequestCreated } from "./triggers/account-deletion-request.created";
import { analysisRequestCreated } from "./triggers/analysis-request-created.trigger";
import { userAuthCreated } from "./triggers/auth-created.trigger";
import { communicationCreated } from "./triggers/communication-created.trigger";
import { credentialsCreated } from "./triggers/credential-created.trigger";
import { exportRequestCreated } from "./triggers/export-request-created.trigger";
import { healthProfileWrittenTrigger } from "./triggers/health-profile-written.trigger";
import { productImportCreated } from "./triggers/product-import-created.trigger";
import { profileUpdated } from "./triggers/profile-updated.trigger";
import { scheduledRun } from "./triggers/scheduler.trigger";
import { servingCreatedTrigger } from "./triggers/serving-created.trigger";
import { servingDeletedTrigger } from "./triggers/serving-deleted.trigger";
import { storageTrigger } from "./triggers/storage.trigger";
import { visionDocumentUpdated } from "./triggers/vision-document-updated.trigger";

const FIREBASE_APP = initializeApp();
const FIRESTORE = initializeFirestore(FIREBASE_APP);
FIRESTORE.settings({ ignoreUndefinedProperties: true });
console.log("Firebase app initialized", { firebaseApp: FIREBASE_APP.name, firestore: FIRESTORE.databaseId });

exports.authCreated = userAuthCreated;
exports.credentialsCreated = credentialsCreated;
exports.communicationCreated = communicationCreated;
exports.analysisCreated = analysisRequestCreated;
exports.exportRequestCreated = exportRequestCreated;
exports.api = expressApiHandler;
exports.scheduler = scheduledRun;
exports.storage = storageTrigger;
exports.profileUpdated = profileUpdated;
exports.healthProfileWritten = healthProfileWrittenTrigger;
exports.servingCreatedTrigger = servingCreatedTrigger;
exports.servingDeletedTrigger = servingDeletedTrigger;
exports.visionDocumentUpdated = visionDocumentUpdated;
exports.productImportCreated = productImportCreated;
exports.accountDeletionRequestCreated = accountDeletionRequestCreated;
