import { AnalysisResultDb, NutritionType, ServingDb } from "@aicoach/shared";
import { Timestamp } from "firebase-admin/firestore";
import { logger } from "firebase-functions";

type ServingForLLM = {
	date: string;
	food: string;
	size: string;
	group: string;
	meal: string;
	[key: string]: string | number;
};

export function formatAnalysisResult(analysisResult: AnalysisResultDb): string {
	const escapeHtml = (text: string): string => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

	const createdDate = analysisResult.created instanceof Timestamp ? analysisResult.created.toDate().toLocaleDateString() : "Unknown Date";

	let result = "<b>Diet Analysis Result</b>\n";
	result += `<i>Generated by ${escapeHtml(analysisResult.model)} on ${createdDate}</i>\n\n`;

	result += "<b>Summary</b>\n";
	result += `${escapeHtml(analysisResult.summary)}\n\n`;

	result += "<b>Score</b>\n";
	result += `${analysisResult.score}/100\n\n`;

	result += "<b>Positives</b>\n";
	if (analysisResult.positives.length > 0) {
		analysisResult.positives.forEach((pos) => {
			result += `- ${escapeHtml(pos.foodName)}: ${escapeHtml(pos.comment)}\n`;
		});
	} else {
		result += "<i>No positive highlights identified.</i>\n";
	}
	result += "\n";

	result += "<b>Negatives</b>\n";
	if (analysisResult.negatives.length > 0) {
		analysisResult.negatives.forEach((neg) => {
			result += `- ${escapeHtml(neg.foodName)}: ${escapeHtml(neg.comment)}\n`;
		});
	} else {
		result += "<i>No negative highlights identified.</i>\n";
	}
	result += "\n";

	result += "<b>Suggestions</b>\n";
	if (analysisResult.suggestions.length > 0) {
		analysisResult.suggestions.forEach((sug, index) => {
			result += `${index + 1}. ${escapeHtml(sug)}\n`;
		});
	} else {
		result += "<i>No suggestions provided.</i>\n";
	}

	return result;
}

export async function formatServings(servings: ServingDb[]): Promise<string> {
	logger.info(`Formatting ${servings.length} servings for LLM...`);
	const simplifiedServings = servings
		.filter((serving) => serving.food)
		.map((serving) => {
			const item: ServingForLLM = {
				date: formatTimestampToString(serving.created as Timestamp),
				food: `${serving.food.brand ? serving.food.brand + ", " : ""}${serving.food.name}`,
				size: `${serving.servingSize.gramWeight || ""}${serving.servingSize.name}`,
				group: serving.food.category,
				meal: serving.category
			};

			const keyNutrients: NutritionType[] = [
				"Calories",
				"Protein",
				"Carbohydrates",
				"Total Fat",
				"Saturated Fat",
				"Sugar",
				"Fiber",
				"Sodium",
				"Cholesterol",
				"Potassium",
				"Calcium",
				"Iron",
				"Vitamin B-6",
				"Vitamin C",
				"Vitamin D"
			];

			for (const type of keyNutrients) {
				const nutrition = serving.food.nutritions.find((n) => n.type === type);
				const amount = nutrition?.amount;

				if (!amount || amount === 0) {
					continue;
				}

				item[type] = `${Number(amount.toFixed(2))} ${nutrition.unit}`;
			}

			return item;
		});

	return JSON.stringify(simplifiedServings);
}

function formatTimestampToString(timestamp: Timestamp): string {
	return timestamp.toDate().toISOString().split("T")[0];
}
