export const DIET_GOALS = [
	"Weight loss",
	"Weight gain",
	"Muscle building",
	"Maintenance",
	"Improved energy",
	"Better digestion",
	"Reduced inflammation",
	"Balanced nutrition",
	"Athletic performance",
	"Hormone balance",
	"Heart health",
	"Blood sugar management",
	"Longevity",
	"Mental clarity",
	"Gut health",
	"Immune support",
	"Pregnancy nutrition",
	"Post-workout recovery",
	"Sustainable eating",
	"Plant-based transition"
];

export const DIETARY_RESTRICTIONS = [
	"Vegetarian",
	"Vegan",
	"Pescatarian",
	"Gluten-free",
	"Dairy-free",
	"Nut-free",
	"Soy-free",
	"Kosher",
	"Halal",
	"Low FODMAP",
	"Paleo",
	"Keto",
	"No added sugar",
	"No artificial ingredients",
	"Low sodium",
	"Egg-free",
	"Shellfish allergy",
	"Grain-free",
	"Nightshade-free",
	"Low histamine"
];

export const HEALTH_CONDITIONS = [
	"Diabetes (Type 1)",
	"Diabetes (Type 2)",
	"Hypertension",
	"High cholesterol",
	"Heart disease",
	"Irritable bowel syndrome",
	"Crohn's disease",
	"Ulcerative colitis",
	"Celiac disease",
	"GERD/Acid reflux",
	"Hypothyroidism",
	"Hyperthyroidism",
	"PCOS",
	"Osteoporosis",
	"Arthritis",
	"Fatty liver disease",
	"Kidney disease",
	"Food allergies",
	"Insulin resistance",
	"Metabolic syndrome"
];
