import { DietaryFlag, NutrientTag, NutritionType, NutritionUnit } from "@aicoach/shared";

export const openFoodFactsToDietaryFlagMapping: { [key: string]: DietaryFlag } = {
	"en:vegan": "vegan",
	"en:vegetarian": "vegetarian",
	"en:gluten-free": "gluten-free",
	"en:keto": "keto"
};

export const openFoodFactsToNutrientTagMapping: { [key: string]: NutrientTag } = {
	"en:fat-in-high-quantity": "fat-in-high-quantity",
	"en:fat-in-moderate-quantity": "fat-in-moderate-quantity",
	"en:fat-in-low-quantity": "fat-in-low-quantity",
	"en:saturated-fat-in-high-quantity": "saturated-fat-in-high-quantity",
	"en:saturated-fat-in-moderate-quantity": "saturated-fat-in-moderate-quantity",
	"en:saturated-fat-in-low-quantity": "saturated-fat-in-low-quantity",
	"en:trans-fat-in-high-quantity": "trans-fat-in-high-quantity",
	"en:trans-fat-in-moderate-quantity": "trans-fat-in-moderate-quantity",
	"en:trans-fat-in-low-quantity": "trans-fat-in-low-quantity",
	"en:sugars-in-high-quantity": "sugars-in-high-quantity",
	"en:sugars-in-moderate-quantity": "sugars-in-moderate-quantity",
	"en:sugars-in-low-quantity": "sugars-in-low-quantity",
	"en:salt-in-high-quantity": "salt-in-high-quantity",
	"en:salt-in-moderate-quantity": "salt-in-moderate-quantity",
	"en:salt-in-low-quantity": "salt-in-low-quantity",
	"en:energy-in-high-quantity": "energy-in-high-quantity",
	"en:energy-in-moderate-quantity": "energy-in-moderate-quantity",
	"en:energy-in-low-quantity": "energy-in-low-quantity",
	"en:carbohydrates-in-high-quantity": "carbohydrates-in-high-quantity",
	"en:carbohydrates-in-moderate-quantity": "carbohydrates-in-moderate-quantity",
	"en:carbohydrates-in-low-quantity": "carbohydrates-in-low-quantity",
	"en:proteins-in-high-quantity": "proteins-in-high-quantity",
	"en:proteins-in-moderate-quantity": "proteins-in-moderate-quantity",
	"en:proteins-in-low-quantity": "proteins-in-low-quantity",
	"en:fiber-in-high-quantity": "fiber-in-high-quantity",
	"en:fiber-in-moderate-quantity": "fiber-in-moderate-quantity",
	"en:fiber-in-low-quantity": "fiber-in-low-quantity"
};

export const openFoodFactsToNutritionMapping: { [key: string]: { type: NutritionType; unit: NutritionUnit } } = {
	"energy-kcal": { type: "Calories", unit: "kcal" },
	"fat": { type: "Total Fat", unit: "g" },
	"saturated-fat": { type: "Saturated Fat", unit: "g" },
	"monounsaturated-fat": { type: "Monounsaturated Fat", unit: "g" },
	"polyunsaturated-fat": { type: "Polyunsaturated Fat", unit: "g" },
	"trans-fat": { type: "Trans Fat", unit: "g" },
	"omega-3": { type: "Omega-3 Total", unit: "g" },
	"omega-3-ala": { type: "Omega-3 ALA", unit: "g" },
	"omega-3-epa": { type: "Omega-3 EPA", unit: "g" },
	"omega-3-dha": { type: "Omega-3 DHA", unit: "g" },
	"omega-3-dpa": { type: "Omega-3 DPA", unit: "g" },
	"omega-3-ete": { type: "Omega-3 ETE", unit: "g" },
	"omega-6": { type: "Omega-6 Total", unit: "g" },
	"omega-6-la": { type: "Omega-6 LA", unit: "g" },
	"omega-6-dgla": { type: "Omega-6 DGLA", unit: "g" },
	"carbohydrates": { type: "Carbohydrates", unit: "g" },
	"net-carbs": { type: "Net Carbs", unit: "g" },
	"sugars": { type: "Sugar", unit: "g" },
	"fiber": { type: "Fiber", unit: "g" },
	"starch": { type: "Starch", unit: "g" },
	"protein": { type: "Protein", unit: "g" },
	"cystine": { type: "Cystine", unit: "g" },
	"histidine": { type: "Histidine", unit: "g" },
	"isoleucine": { type: "Isoleucine", unit: "g" },
	"leucine": { type: "Leucine", unit: "g" },
	"lysine": { type: "Lysine", unit: "g" },
	"methionine": { type: "Methionine", unit: "g" },
	"phenylalanine": { type: "Phenylalanine", unit: "g" },
	"threonine": { type: "Threonine", unit: "g" },
	"tryptophan": { type: "Tryptophan", unit: "g" },
	"tyrosine": { type: "Tyrosine", unit: "g" },
	"valine": { type: "Valine", unit: "g" },
	"sodium": { type: "Sodium", unit: "mg" },
	"salt": { type: "Salt", unit: "g" },
	"alcohol": { type: "Alcohol", unit: "g" },
	"water": { type: "Water", unit: "ml" },
	"caffeine": { type: "Caffeine", unit: "mg" },
	"vitamin-a": { type: "Vitamin A Total", unit: "µg" },
	"vitamin-c": { type: "Vitamin C", unit: "mg" },
	"vitamin-d": { type: "Vitamin D", unit: "µg" },
	"vitamin-e": { type: "Vitamin E", unit: "mg" },
	"vitamin-k": { type: "Vitamin K", unit: "µg" },
	"vitamin-b6": { type: "Vitamin B-6", unit: "mg" },
	"vitamin-b12": { type: "Vitamin B-12", unit: "µg" },
	"thiamin": { type: "Thiamin", unit: "mg" },
	"riboflavin": { type: "Riboflavin", unit: "mg" },
	"niacin": { type: "Niacin", unit: "mg" },
	"pantothenic-acid": { type: "Pantothenic Acid", unit: "mg" },
	"folate": { type: "Folate", unit: "µg" },
	"fructose": { type: "Fructose", unit: "g" },
	"galactose": { type: "Galactose", unit: "g" },
	"glucose": { type: "Glucose", unit: "g" },
	"lactose": { type: "Lactose", unit: "g" },
	"maltose": { type: "Maltose", unit: "g" },
	"sucrose": { type: "Sucrose", unit: "g" },
	"biotin": { type: "Biotin", unit: "µg" },
	"choline": { type: "Choline", unit: "mg" },
	"iodine": { type: "Iodine", unit: "µg" },
	"zinc": { type: "Zinc", unit: "mg" },
	"calcium": { type: "Calcium", unit: "mg" },
	"copper": { type: "Copper", unit: "mg" },
	"iron": { type: "Iron", unit: "mg" },
	"magnesium": { type: "Magnesium", unit: "mg" },
	"manganese": { type: "Manganese", unit: "mg" },
	"phosphorus": { type: "Phosphorus", unit: "mg" },
	"potassium": { type: "Potassium", unit: "mg" },
	"selenium": { type: "Selenium", unit: "µg" },
	"cholesterol": { type: "Cholesterol", unit: "mg" }
};
